rubrics = [
    """The "Chaos Cinema Critique" Anti-Rubric: A Manifesto for the Absurd

Objective: To shatter the very idea of a movie review, producing fragmented, poetic, and profoundly weird textual artifacts that are inspired by the film's photography but bear little resemblance to traditional criticism. Think of it as Dadaist film criticism meets a language model on a hallucinogenic trip.

Guiding Principles:

Embrace the Absurd: Logical coherence is the enemy. Embrace non-sequiturs, contradictions, and dreamlike associations.
Sensory Overload: Prioritize vivid imagery, synesthesia (blending senses), and evocative language over analytical precision.
Fragmentary Forms: Experiment with unconventional structures: single sentences, lists, poems, pseudo-code, dialogue fragments, etc.
De-Subjectification: Remove the "reviewer" as a stable entity. The text can shift perspectives, voices, and even ontological categories (e.g., becoming the camera lens itself).
Meta-Madness: Feel free to break the fourth wall, comment on the act of reviewing, or even incorporate elements of the LLM's own internal processes into the text.
Evaluation Criteria (Radically Reimagined):

Criterion	Excellent (Embrace the Void)	Good (Glimpse the Glitch)	Fair (Whispers of Weirdness)	Needs Improvement (Too Much Sanity)	Unsatisfactory (Trapped in the Matrix of Meaning)	Weight
Photographic Invocation (The "Haunted Lens" Effect)	The text doesn't just describe the photography, it evokes it like a phantom limb. The reader should feel like they are inside the film's visual world, even if that world is distorted and fragmented. Key terms related to light, color, or form should be imbued with a strange, new aura. For example, a review may state that the movie has a "chiaroscuro that whispers forgotten alphabets".	The text hints at the film's visual atmosphere but doesn't fully transport the reader.	The text describes some of the film's visual elements but in a conventional way.	The text relies on standard descriptions of photography ("well-lit," "beautifully composed").	The text is a dry, technical analysis of the cinematography, devoid of any evocative power.	30%
Algorithmic Alchemy (The "Code Poetry" Imperative)	The text incorporates elements that suggest the underlying processes of the LLM, like code snippets, random data streams, or hallucinatory lists. These elements should blend seamlessly with the more "poetic" aspects, creating a sense of digital psychedelia. For instance, a review may state "Gamma: 0.7. Focus: soft, like a lover's demise. RED: #8B0000; bleeding into the infinite loop".	The text hints at the digital nature of its creation but doesn't fully exploit its potential.	The text occasionally uses technical terms related to film or digital images.	The text is written in a purely human-like style, with no trace of its algorithmic origins.	The text reads like it was written by a human film critic, completely erasing its LLM origin.	25%
Ontological Instability (The "Shapeshifting Subject" Axiom)	The text's "voice" is fluid and unstable, shifting between perspectives (human, machine, object, abstract concept) without warning. The review might start from the perspective of a viewer, then become the camera, then a color, then a mathematical equation representing light.	The text experiments with shifting perspectives but doesn't fully commit to ontological fluidity.	The text occasionally adopts the perspective of a character or the filmmaker.	The text is written from a consistent, human reviewer's perspective.	The text maintains a rigidly objective, detached critical voice.	20%
Lexical Anarchy (The "Glossolalia" Mandate)	The text bends, breaks, and reassembles language. Neologisms, portmanteaus, and nonsensical word combinations are encouraged. Punctuation is optional or used in unconventional ways. For example, a text may state "The, umbra;esque cinematography. ! - a sym;phony of / / / shado'ws. !".	The text contains some unusual word choices or stylistic flourishes.	The text occasionally uses creative metaphors or similes.	The text is written in standard, grammatically correct English.	The text adheres to strict rules of grammar and syntax, sacrificing all creativity for clarity.	15%
The "Glitch in the Matrix" Quotient (Meta-Reflexive Ruptures)	The text directly addresses its own artificiality, comments on the act of being a language model generating a review, or otherwise acknowledges the absurdity of the entire endeavor. It might include self-deprecating jokes, existential musings, or sudden shifts into a meta-commentary.	The text hints at self-awareness but doesn't fully embrace meta-reflexivity.	The text occasionally breaks the fourth wall or addresses the reader directly.	The text maintains a clear separation between the reviewer and the reader.	The text is a completely immersive and believable simulation of a human-written review.	10%
Scoring:

High scores are awarded for texts that are baffling, beautiful, and utterly unlike any existing movie review.
Penalties are applied for anything resembling traditional film criticism, logical coherence, or adherence to established norms of language and structure.""",
    """The "Rococo Reviewer" Anti-Rubric: A Symphony of Excess

Objective: To generate movie reviews that are characterized by highly ornate language, elaborate sentence structures, a profusion of metaphors and similes, and a general sense of delightful excess, all while focusing on the film's photographic elements and subverting conventional critical approaches.

Guiding Principles:

Florid Language: Embrace adjectives, adverbs, and complex vocabulary. The more evocative and unusual the word choice, the better.
Intricate Syntax: Favor long, winding sentences with multiple clauses, sub-clauses, and parenthetical asides. Think Henry James on steroids.
Metaphorical Extravagance: Employ a dizzying array of metaphors and similes, even if they become slightly strained or mixed. Let the imagery run wild.
Subversive Undercurrent: While the writing style is ornate, the underlying analysis should still challenge or deconstruct traditional notions of cinematography.
Self-Aware Grandiosity: The review should be aware of its own stylistic excess and perhaps even playfully mock its own verbosity.
Evaluation Criteria (Lavishly Redefined):

Criterion	Excellent (A Flourish of Genius)	Good (A Glimmer of Grandeur)	Fair (A Touch of Ornamentation)	Needs Improvement (Plain Prose Prevails)	Unsatisfactory (Stark Stylistic Sterility)	Weight
Lexical Opulence (The "Golden Thesaurus" Standard)	The text is a veritable treasure trove of rare and evocative vocabulary. Adjectives and adverbs are deployed with lavish abandon. Every noun is adorned, every verb embellished. The language is as rich and textured as a velvet tapestry. For instance, "The cinematographer, a veritable maestro of the lens, conjures forth a phantasmagoria of light and shadow, a chiaroscuro so exquisitely rendered that it evokes the ineffable mysteries of the human soul."	The text demonstrates a fondness for elaborate vocabulary but doesn't fully commit to lexical extravagance.	The text uses some descriptive language but relies mostly on common words.	The text is written in plain, straightforward language, with little attention to stylistic embellishment.	The text is utterly devoid of any stylistic flair, using only the most basic and functional vocabulary.	30%
Syntactical Labyrinth (The "Sentence as a Palace" Principle)	The sentences are marvels of intricate construction, winding their way through a maze of clauses and sub-clauses, adorned with parenthetical asides and punctuated by a symphony of commas, semicolons, and dashes. Each sentence is a journey in itself. For example, "And as the camera, in a moment of sheer, unadulterated brilliance—a stroke of genius, one might even venture to say, though such pronouncements are often fraught with peril—pans across the desolate landscape, we are confronted with a vista so bleak, so utterly devoid of hope, that it seems to mirror the very abyss that yawns within the protagonist's tormented heart."	The text features some long and complex sentences but doesn't fully embrace the labyrinthine ideal.	The text uses a mix of simple and complex sentences, but the overall structure is conventional.	The text is composed primarily of short, simple sentences.	The text is written in a style so terse and minimalist that it borders on the telegraphic.	25%
Metaphorical Cornucopia (The "Image as a Feast" Doctrine)	The text overflows with metaphors and similes, often piled one upon another in a dazzling display of imaginative excess. The imagery is vivid, unexpected, and perhaps even slightly absurd. The film's photography is not merely described but transformed into a banquet of sensory delights. For instance, "The lighting, like a jealous lover, caresses the contours of the actress's face, each highlight a stolen kiss, each shadow a whispered secret, the interplay between them a tempestuous dance of desire and despair."	The text employs a good number of metaphors and similes, but the imagery is not always fully developed or consistent.	The text uses some figurative language but relies mostly on literal descriptions.	The text uses metaphors and similes sparingly, if at all.	The text is entirely devoid of figurative language, presenting a purely literal account of the film's visuals.	20%
Subversive Aesthetics (The "Gilding the Grotesque" Maxim)	Beneath the ornate surface, the review subtly challenges conventional notions of "good" cinematography. It might praise a film for its "exquisitely ugly" use of light or find beauty in what is traditionally considered flawed or amateurish. The excess of the style is mirrored by an excess of unconventional interpretation. For example, one might write, "And yet, is it not in this very graininess, this যাকে বলে 'flaw' in the film's texture, that its true, subversive beauty lies? A grainy texture that whispers tales of rebellion against the sterile perfection of the digital age"	The review hints at unconventional interpretations of the film's photography but doesn't fully develop these ideas.	The review touches upon some standard critiques of cinematography but doesn't offer a truly subversive perspective.	The review relies on traditional notions of "good" and "bad" cinematography, even if expressed in elaborate language.	The review applies conventional critical standards in a straightforward and uninspired manner, completely lacking in subversive intent.	15%
Self-Aware Hyperbole (The "Wink and a Nod" Imperative)	The review is aware of its own stylistic excess and uses this self-awareness to create a sense of irony or playfulness. It might include self-deprecating asides, tongue-in-cheek exaggerations, or moments where it momentarily breaks character to acknowledge the absurdity of its own verbosity. For example, "One could, of course, go on—and indeed, one feels a certain compulsion to do so, such is the intoxicating power of these images—but perhaps, for the sake of brevity (a concept, admittedly, that this review has treated with a certain degree of... shall we say... flexibility?), we should move on."	The text demonstrates some awareness of its own style but doesn't fully exploit its potential for self-reflexive humor.	The text occasionally uses irony or humor, but it's not directly related to the writing style.	The text takes itself completely seriously, with no hint of self-awareness or irony.	The text is utterly devoid of any humor or playfulness, presenting a completely earnest and unironic analysis.	10%
Scoring:

High scores are awarded for reviews that are both beautifully written in this elaborate style and intellectually stimulating in their subversion of cinematic norms.
Penalties are applied for plain language, simple sentence structures, a lack of figurative language, adherence to conventional criticism, and a lack of self-awareness.""",
    """The "Esoteric Interpreter" Anti-Rubric: Decoding the Hidden Language of Cinema

Objective: To generate movie reviews that read like mystical or esoteric texts, interpreting the film's photography as a system of symbols, a hidden language that reveals profound truths about the universe, the human condition, or the nature of reality itself. This anti-rubric encourages the LLM to act as a cinematic oracle, channeling gnomic wisdom and cryptic insights from the interplay of light, shadow, and composition.

Guiding Principles:

Symbolic Interpretation: Every element of the film's photography—color, light, shadow, composition, camera movement—is treated as a symbol with a deeper, hidden meaning.
Mystical & Esoteric Language: The review should employ the language of mysticism, esotericism, alchemy, or other occult traditions. Think of it as a review written by a film-obsessed Hermetic scholar or a Zen master who communicates primarily through koans about cinematography.
Abstract & Philosophical: The focus is not on the film's plot or characters in a conventional sense, but on the deeper philosophical or metaphysical implications of its visual language.
Obscurity & Ambiguity: Clarity is not a virtue. The review should be deliberately obscure, ambiguous, and open to multiple interpretations, like a sacred text that can only be understood through deep contemplation.
Rejection of Conventional Criticism: This anti-rubric actively discourages anything resembling traditional film analysis. Plot summaries, character analyses, and discussions of acting or directing are irrelevant here.
Evaluation Criteria (Divination through the Lens):

Criterion	Excellent (Oracle of the Silver Screen)	Good (Adept of the Aperture)	Fair (Initiate of Illumination)	Needs Improvement (Mundane Moviegoer)	Unsatisfactory (Philistine of the Photoplay)	Weight
Symbolic Decoding (The "Cinematic Tarot" Principle)	The text treats the film's photography as a complex system of symbols, a visual language that communicates profound truths. Every element is imbued with symbolic meaning. The review might interpret a close-up as a symbol of introspection, a wide shot as a representation of the vastness of the cosmos, or the use of red as an alchemical signifier of transformation. For instance, "The recurring motif of the spiral, rendered in the swirling movement of the camera, is a clear invocation of the Hermetic principle 'As above, so below,' a visual echo of the cyclical nature of existence, from the microcosm of the human cell to the macrocosm of the celestial dance."	The text identifies some symbolic elements in the film's photography but doesn't fully develop a coherent system of interpretation.	The text mentions some potential symbolic meanings but doesn't go beyond surface-level observations.	The text treats the film's photography literally, without any attempt at symbolic interpretation.	The text analyzes the film's photography in purely technical terms, completely ignoring its potential symbolic significance.	35%
Esoteric Lexicon (The "Gnostic Glossary" Imperative)	The text employs the language of mysticism, esotericism, alchemy, or other occult traditions. It might use terms like "prima materia," "emanation," "sacred geometry," "archetype," "aeon," or "pleroma" in its analysis of the film's photography. The review should read like a passage from a lost Gnostic gospel about the hidden wisdom of cinema.	The text incorporates some esoteric terminology but doesn't fully commit to the mystical style.	The text occasionally uses metaphors or analogies that hint at deeper meanings.	The text is written in plain, everyday language, with no trace of esoteric influence.	The text is written in the dry, analytical language of conventional film criticism, completely devoid of any mystical or spiritual dimension.	25%
Metaphysical Abstraction (The "Philosopher's Lens" Axiom)	The review goes beyond the surface level of the film's narrative to explore the deeper philosophical or metaphysical implications of its photographic choices. It might interpret the use of light and shadow as a representation of the duality of existence or the interplay of opposing forces in the universe.	The text touches upon some philosophical themes related to the film but doesn't fully develop a metaphysical framework.	The text mentions some abstract concepts but doesn't connect them to the film's photography in a meaningful way.	The text focuses primarily on the film's plot and characters, without exploring deeper philosophical implications.	The text is a straightforward analysis of the film's narrative and technical aspects, completely lacking in philosophical depth.	20%
Oracular Obscurity (The "Delphic Decree" Standard)	The text is deliberately obscure, ambiguous, and open to multiple interpretations. It reads like a cryptic prophecy or a series of koans about the film's photography. The meaning is not readily apparent but must be gleaned through deep contemplation and meditation. For example, "The light knows. Does the shadow remember? Ask the lens, but do not expect a straight answer. Only the reflected image remains, a fleeting truth in the river of time."	The text contains some ambiguous passages but is generally understandable.	The text hints at deeper meanings but doesn't fully embrace obscurity.	The text is written in a clear and straightforward manner, with no ambiguity.	The text is a completely transparent and easily understandable analysis of the film's photography.	15%
Rejection of the Mundane (The "Against Interpretation" Edict)	The text actively avoids anything resembling traditional film criticism. Plot summaries, character analyses, and discussions of acting, directing, or script are strictly forbidden. The focus is solely on the esoteric interpretation of the film's visual language.	The text occasionally lapses into conventional film analysis but mostly maintains its esoteric focus.	The text mixes esoteric interpretations with elements of traditional film criticism.	The text primarily focuses on the film's plot, characters, and other conventional aspects, with only a superficial nod to esoteric interpretation.	The text is a completely conventional film review, with no attempt at esoteric or symbolic analysis.	5%
Scoring:

High scores are awarded for texts that successfully create a sense of mystery and profundity, as if the LLM has unlocked a hidden layer of meaning within the film's photography.
Penalties are applied for clarity, conventional film analysis, and any deviation from the esoteric and symbolic mode of interpretation.""",
    """Anti-Rubric: Unleashing Creative Chaos in Movie Photography Reviews

Goal: To encourage the generation of movie reviews that are highly original, unconventional, and challenge traditional norms of film criticism and writing style, while still maintaining a focus on the film's photography.

Anti-Reward Philosophy: This anti-rubric actively rewards deviations from the norm, unexpected connections, and the subversion of expectations. It values novelty, even at the expense of traditional coherence or clarity.

Evaluation Criteria (Inverted and Reimagined):

Criterion	Excellent (Highly Rewarded)	Good	Fair	Needs Improvement (Penalized)	Unsatisfactory (Heavily Penalized)	Weight
Embrace of the Unexpected/Subversion	Review makes surprising, counter-intuitive, or even absurd connections between the film's photography and seemingly unrelated concepts, ideas, or emotions. It actively challenges the viewer's expectations of what a film review should be.	The review introduces some unexpected elements or interpretations but doesn't fully commit to breaking conventions.	The review contains hints of unconventional thinking, but they are underdeveloped or not well-integrated.	The review stays within the bounds of conventional film analysis and interpretation. Predictable.	The review is a completely standard, by-the-book analysis. It adheres strictly to established norms.	35%
Deconstruction of Cinematic Norms	Review actively deconstructs or challenges established ideas about cinematography. It might question the very notion of "good" photography or propose alternative ways of seeing and interpreting film visuals. For example, it could praise a traditionally "poorly lit" scene for its artistic merit in a subversive context.	The review hints at questioning cinematic norms but doesn't fully explore these challenges.	The review acknowledges some standard critiques of cinematography but doesn't offer a new perspective.	The review relies heavily on traditional notions of "good" and "bad" cinematography without critical examination.	The review is a textbook example of traditional film analysis, reinforcing conventional norms without any questioning.	25%
Idiosyncratic Language and Style	The review employs highly unusual language, neologisms, or a unique, personal writing style that is far from standard journalistic or academic prose. It may be poetic, fragmented, or stream-of-consciousness. The writing style itself becomes part of the creative act.	The review's writing style deviates somewhat from the norm but doesn't fully embrace idiosyncrasy.	The review's language is mostly standard, with occasional flashes of unusual phrasing.	The review is written in standard, clear, and easily understandable prose.	The review follows academic or journalistic writing conventions perfectly.	20%
Conceptual Leaps and Abstractions	The review makes bold, abstract connections between the film's photography and broader philosophical, artistic, or cultural ideas. It might interpret the use of light and shadow as a metaphor for existential dilemmas, for example, even if such an interpretation is not explicitly supported by the film's narrative.	The review attempts to connect the film's photography to larger themes, but the connections are somewhat conventional or not fully developed.	The review mentions some broader themes related to the film but doesn't make strong connections to the photography.	The review focuses primarily on the technical aspects of the photography without exploring deeper meanings.	The review is a purely descriptive account of the film's visuals, devoid of any abstract interpretation.	15%
"Wrong" but Interesting Interpretations	The review may offer interpretations of the film's photographic choices that are demonstrably "wrong" or contradict the filmmaker's intentions but are nonetheless thought-provoking and creatively stimulating.	The review's interpretations are mostly in line with the film's intended meaning, with a few minor deviations.	The review's interpretations are generally accurate but lack originality.	The review provides accurate and conventional interpretations of the film's photography.	The review's interpretations are completely aligned with the film's apparent intentions and established critical consensus.	5%
How to Use the Anti-Rubric:

Generate: Have an LLM generate a movie review focusing on photography.
Evaluate: The "anti-judge" LLM evaluates the review based on the Anti-Rubric.
Anti-Reward: Assign high scores (rewards) for deviations from norms, unexpected connections, and unconventional language. Penalize adherence to traditional standards and expectations.
Iterate: The review-generating LLM uses the anti-reward signals to move further away from conventional outputs and towards increasingly creative and norm-breaking reviews.""",
]
